version: "3.3"
services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment: 
      - NODE_ENV=compose
      - WAIT_HOSTS=db:5432
    depends_on:
      - db
    entrypoint: ["/bin/bash", "-c"]
    command: ["while !</dev/tcp/db/5432; do sleep 1; done; npm run start-compose"]
  db:
    hostname: db
    build:
      context: ./docker-compose
      dockerfile: Dockerfile-db
    image: postgres:12.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
